SELECT
  name,
  CASE WHEN SUM(CASE WHEN flg = "01" THEN 1 ELSE NULL END) = 1 THEN "〇" ELSE NULL END AS "01",
  CASE WHEN SUM(CASE WHEN flg = "02" THEN 1 ELSE NULL END) = 1 THEN "〇" ELSE NULL END AS "02",
  CASE WHEN SUM(CASE WHEN flg = "03" THEN 1 ELSE NULL END) = 1 THEN "〇" ELSE NULL END AS "03",
  CASE WHEN SUM(CASE WHEN flg = "04" THEN 1 ELSE NULL END) = 1 THEN "〇" ELSE NULL END AS "04"
FROM 
  Table_A
GROUP BY
  name
